### ISSUE TITLE
incorrect napLoop ? 

### ISSUE THREAD

**Issue by weepy** [sam-js/sam-devtools#10]
Hi I was just wonder if I'm reading the code wrong : 

```
        if (tooManyPresentsFromNAP) {
          return present({ '@@napLoop': 'too many present()s from NAP' })
        }

        const secondLastSnapshot = snapshots[snapshots.length -2]
        const ineffectiveNAP = fromNap(lastSnapshot) && fromNap(secondLastSnapshot) && deepEqual(lastSnapshot.store, secondLastSnapshot.store)
        if (ineffectiveNAP) {
          return present({ '@@napLoop': 'last present() from NAP didn\'t change the store' })
        }
```

should these be `@@nap` instead ?

**Comment by gunar** [comment]
Nope, that's right. `@@napLoop` is a flag DevTools sends to the UI, signaling nap has entered a infinite loop and was stopped.

**Comment by weepy** [comment]
but   `'\@@napLoop': 'last present() from NAP didn\'t change the store'` isn't from an infinite loop ?

**Comment by gunar** [comment]
Sorry I don't follow. When DevTools identifies that a nap didn't change the store, it knows for sure we're in an infinite nap loop. That's why it sends this signal to the UI, so the developer may understand what halted the execution.

**Comment by weepy** [comment]
Oh I see. sorry my bad. ^_^
